export const services = [
  {
    id: "1",
    title: "Web Development",
    description: "Custom development for your needs",
    img: "https://cdn.pixabay.com/photo/2021/08/04/13/06/software-developer-6521720_1280.jpg",
    features: ["", ""],
    tools: [],
    type: "Engineering",
  },
  {
    id: "2",
    title: "Mobile App Development",
    description: "Custom development for your needs",
    img: "https://cdn.pixabay.com/photo/2015/02/02/11/09/office-620822_1280.jpg",
    features: ["Abc", "123"],
    tools: [],
    type: "Engineering",
  },
  {
    id: "3",
    title: "Cloud Solutions (COMING SOON)",
    description: "Custom development for your needs",
    img: "https://cdn.pixabay.com/photo/2015/07/17/22/43/student-849825_1280.jpg",
    features: ["Abc", "123"],
    tools: [],
    type: "Engineering",
  },
  {
    id: "4",
    title: "System Design (COMING SOON)",
    description: "Custom development for your needs",
    img: "https://cdn.pixabay.com/photo/2017/06/28/10/06/binary-2450153_1280.jpg",
    features: ["Abc", "123"],
    tools: [],
    type: "Engineering",
  },
  {
    id: "5",
    title: "Digital Marketing",
    description: "Custom development for your needs",
    img: "https://cdn.pixabay.com/photo/2016/03/09/13/58/online-marketing-1246457_1280.jpg",
    features: ["Abc", "123"],
    tools: [],
    type: "Marketing",
  },
  {
    id: "6",
    title: "Data Analytics",
    description: "Custom development for your needs",
    img: "https://cdn.pixabay.com/photo/2016/11/23/14/37/blur-1853262_1280.jpg",
    features: ["Abc", "123"],
    tools: [],
    type: "Data",
  },
];

export const filterKeys = ["Engineering", "Marketing", "Data", "Clear X"];
